import re
from pathlib import Path


SECTION_HEADINGS = {
    "DDL": "ddl",
    "Transformation SQL": "transformation_sql",
    "Validation Queries": "validation_queries",
}

SQL_FENCE_PATTERN = re.compile(r"```sql\s*(.*?)```", re.IGNORECASE | re.DOTALL)
H2_PATTERN = re.compile(r"^##\s+(.+?)\s*$", re.MULTILINE)


def _split_h2_sections(markdown_text: str) -> dict[str, str]:
    matches = list(H2_PATTERN.finditer(markdown_text))
    if not matches:
        raise ValueError("Agent response did not contain any H2 sections.")

    sections: dict[str, str] = {}
    for index, match in enumerate(matches):
        heading = match.group(1).strip()
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(markdown_text)
        sections[heading] = markdown_text[start:end].strip()
    return sections


def _extract_sql_blocks(section_body: str, heading: str) -> str:
    blocks = [block.strip() for block in SQL_FENCE_PATTERN.findall(section_body) if block.strip()]
    if not blocks:
        raise ValueError(f"Section '## {heading}' did not contain a fenced sql code block.")

    return "\n\nGO\n\n".join(blocks)


def extract_sql_sections(markdown_text: str) -> dict[str, str]:
    sections = _split_h2_sections(markdown_text)
    extracted: dict[str, str] = {}

    for heading, key in SECTION_HEADINGS.items():
        if heading not in sections:
            raise ValueError(f"Agent response is missing required section '## {heading}'.")
        extracted[key] = _extract_sql_blocks(sections[heading], heading)

    return extracted


def render_generated_sql(sections: dict[str, str]) -> str:
    required_keys = tuple(SECTION_HEADINGS.values())
    missing = [key for key in required_keys if not sections.get(key)]
    if missing:
        missing_keys = ", ".join(missing)
        raise ValueError(f"Cannot render SQL because required sections are missing: {missing_keys}")

    parts = [
        "-- Generated by app/generate_target_model_sql.py from an agent response.",
        "-- Regenerate this file instead of editing it manually.",
        "",
        "-- DDL",
        sections["ddl"].strip(),
        "",
        "GO",
        "",
        "-- Transformation SQL",
        sections["transformation_sql"].strip(),
        "",
        "GO",
        "",
        "-- Validation Queries",
        sections["validation_queries"].strip(),
        "",
    ]
    return "\n".join(parts)


def write_generated_sql(output_path: Path, sql_text: str) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(sql_text, encoding="utf-8")