-- Generated by app/generate_target_model_sql.py from an agent response.
-- Regenerate this file instead of editing it manually.

-- DDL
-- Dimension tables
CREATE TABLE dbo.dim_patient (
    patient_key INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    patient_id VARCHAR(50) NOT NULL,
    mrn VARCHAR(50) NOT NULL,
    birth_date DATE NOT NULL,
    gender VARCHAR(50) NOT NULL,
    insurance_type VARCHAR(50) NOT NULL,
    zip_code VARCHAR(20) NOT NULL,
    CONSTRAINT uq_dim_patient_patient_id UNIQUE (patient_id)
);

CREATE TABLE dbo.dim_date (
    date_key INT NOT NULL PRIMARY KEY,
    date_value DATE NOT NULL,
    calendar_year INT NOT NULL,
    calendar_month INT NOT NULL,
    month_name VARCHAR(20) NOT NULL,
    day_of_month INT NOT NULL,
    CONSTRAINT uq_dim_date_date_value UNIQUE (date_value)
);

CREATE TABLE dbo.dim_facility (
    facility_key INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    facility_id VARCHAR(50) NOT NULL,
    facility_name VARCHAR(200) NOT NULL,
    region VARCHAR(100) NOT NULL,
    CONSTRAINT uq_dim_facility_facility_id UNIQUE (facility_id)
);

CREATE TABLE dbo.dim_department (
    department_key INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    department_id VARCHAR(50) NOT NULL,
    facility_id VARCHAR(50) NOT NULL,
    department_name VARCHAR(200) NOT NULL,
    department_type VARCHAR(100) NOT NULL,
    bed_count INT NULL,
    CONSTRAINT uq_dim_department_department_id UNIQUE (department_id)
);

CREATE TABLE dbo.dim_diagnosis (
    diagnosis_key INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    icd10_code VARCHAR(20) NOT NULL,
    diagnosis_description VARCHAR(255) NOT NULL,
    CONSTRAINT uq_dim_diagnosis_icd10_code UNIQUE (icd10_code)
);

-- Fact table
CREATE TABLE dbo.fact_encounter_outcomes (
    encounter_id VARCHAR(50) NOT NULL PRIMARY KEY,
    patient_key INT NOT NULL,
    admit_date_key INT NOT NULL,
    discharge_date_key INT NULL,
    facility_key INT NOT NULL,
    department_key INT NOT NULL,
    diagnosis_key INT NULL,
    age_group VARCHAR(50) NOT NULL,
    admit_date DATE NOT NULL,
    discharge_date DATE NULL,
    length_of_stay_days INT NULL,
    encounter_count INT NOT NULL,
    discharge_count INT NOT NULL,
    index_discharge_flag INT NOT NULL,
    readmission_30d_flag INT NOT NULL,
    readmission_count_30d INT NOT NULL,
    CONSTRAINT fk_fact_patient FOREIGN KEY (patient_key) REFERENCES dbo.dim_patient(patient_key),
    CONSTRAINT fk_fact_admit_date FOREIGN KEY (admit_date_key) REFERENCES dbo.dim_date(date_key),
    CONSTRAINT fk_fact_discharge_date FOREIGN KEY (discharge_date_key) REFERENCES dbo.dim_date(date_key),
    CONSTRAINT fk_fact_facility FOREIGN KEY (facility_key) REFERENCES dbo.dim_facility(facility_key),
    CONSTRAINT fk_fact_department FOREIGN KEY (department_key) REFERENCES dbo.dim_department(department_key),
    CONSTRAINT fk_fact_diagnosis FOREIGN KEY (diagnosis_key) REFERENCES dbo.dim_diagnosis(diagnosis_key)
);

GO

-- Transformation SQL
-- Load dim_patient
INSERT INTO dbo.dim_patient (
    patient_id,
    mrn,
    birth_date,
    gender,
    insurance_type,
    zip_code
)
SELECT
    p.patient_id,
    p.mrn,
    p.birth_date,
    p.gender,
    p.insurance_type,
    p.zip_code
FROM patients p;

-- Load dim_facility
INSERT INTO dbo.dim_facility (
    facility_id,
    facility_name,
    region
)
SELECT
    f.facility_id,
    f.facility_name,
    f.region
FROM facilities f;

-- Load dim_department
INSERT INTO dbo.dim_department (
    department_id,
    facility_id,
    department_name,
    department_type,
    bed_count
)
SELECT
    d.department_id,
    d.facility_id,
    d.department_name,
    d.department_type,
    d.bed_count
FROM departments d;

-- Load dim_diagnosis from primary diagnoses only
INSERT INTO dbo.dim_diagnosis (
    icd10_code,
    diagnosis_description
)
SELECT DISTINCT
    dx.icd10_code,
    dx.diagnosis_description
FROM diagnoses dx
WHERE dx.is_primary = 1;

-- Load dim_date from admit and discharge dates
WITH distinct_dates AS (
    SELECT e.admit_date AS date_value
    FROM encounters e
    WHERE e.admit_date IS NOT NULL
    UNION
    SELECT e.discharge_date AS date_value
    FROM encounters e
    WHERE e.discharge_date IS NOT NULL
)
INSERT INTO dbo.dim_date (
    date_key,
    date_value,
    calendar_year,
    calendar_month,
    month_name,
    day_of_month
)
SELECT
    CAST(CONVERT(VARCHAR(8), dd.date_value, 112) AS INT) AS date_key,
    dd.date_value,
    YEAR(dd.date_value) AS calendar_year,
    MONTH(dd.date_value) AS calendar_month,
    DATENAME(MONTH, dd.date_value) AS month_name,
    DAY(dd.date_value) AS day_of_month
FROM distinct_dates dd;

-- Load fact_encounter_outcomes
WITH primary_diagnosis AS (
    SELECT
        dx.encounter_id,
        dx.icd10_code,
        dx.diagnosis_description
    FROM diagnoses dx
    WHERE dx.is_primary = 1
),
sequenced_encounters AS (
    SELECT
        e.encounter_id,
        e.patient_id,
        e.facility_id,
        e.department_id,
        e.admit_date,
        e.discharge_date,
        LEAD(e.admit_date) OVER (
            PARTITION BY e.patient_id
            ORDER BY e.admit_date, e.encounter_id
        ) AS next_admit_date
    FROM encounters e
),
fact_stage AS (
    SELECT
        e.encounter_id,
        e.patient_id,
        e.facility_id,
        e.department_id,
        e.admit_date,
        e.discharge_date,
        pd.icd10_code,
        DATEDIFF(YEAR, p.birth_date, e.admit_date)
            - CASE
                WHEN DATEFROMPARTS(YEAR(e.admit_date), MONTH(p.birth_date), DAY(p.birth_date)) > e.admit_date THEN 1
                ELSE 0
              END AS age_at_admit,
        CASE
            WHEN e.discharge_date IS NOT NULL THEN DATEDIFF(DAY, e.admit_date, e.discharge_date)
            ELSE NULL
        END AS length_of_stay_days,
        CASE
            WHEN e.discharge_date IS NOT NULL THEN 1 ELSE 0
        END AS discharge_count,
        CASE
            WHEN e.discharge_date IS NOT NULL THEN 1 ELSE 0
        END AS index_discharge_flag,
        CASE
            WHEN e.discharge_date IS NOT NULL
             AND se.next_admit_date IS NOT NULL
             AND se.next_admit_date > e.discharge_date
             AND se.next_admit_date <= DATEADD(DAY, 30, e.discharge_date)
            THEN 1 ELSE 0
        END AS readmission_30d_flag
    FROM encounters e
    INNER JOIN patients p
        ON e.patient_id = p.patient_id
    LEFT JOIN primary_diagnosis pd
        ON e.encounter_id = pd.encounter_id
    LEFT JOIN sequenced_encounters se
        ON e.encounter_id = se.encounter_id
)
INSERT INTO dbo.fact_encounter_outcomes (
    encounter_id,
    patient_key,
    admit_date_key,
    discharge_date_key,
    facility_key,
    department_key,
    diagnosis_key,
    age_group,
    admit_date,
    discharge_date,
    length_of_stay_days,
    encounter_count,
    discharge_count,
    index_discharge_flag,
    readmission_30d_flag,
    readmission_count_30d
)
SELECT
    fs.encounter_id,
    dp.patient_key,
    CAST(CONVERT(VARCHAR(8), fs.admit_date, 112) AS INT) AS admit_date_key,
    CASE
        WHEN fs.discharge_date IS NOT NULL
        THEN CAST(CONVERT(VARCHAR(8), fs.discharge_date, 112) AS INT)
        ELSE NULL
    END AS discharge_date_key,
    df.facility_key,
    dd.department_key,
    dx.diagnosis_key,
    CASE
        WHEN fs.age_at_admit < 18 THEN '0-17'
        WHEN fs.age_at_admit BETWEEN 18 AND 34 THEN '18-34'
        WHEN fs.age_at_admit BETWEEN 35 AND 49 THEN '35-49'
        WHEN fs.age_at_admit BETWEEN 50 AND 64 THEN '50-64'
        ELSE '65+'
    END AS age_group,
    fs.admit_date,
    fs.discharge_date,
    fs.length_of_stay_days,
    1 AS encounter_count,
    fs.discharge_count,
    fs.index_discharge_flag,
    fs.readmission_30d_flag,
    fs.readmission_30d_flag AS readmission_count_30d
FROM fact_stage fs
INNER JOIN dbo.dim_patient dp
    ON fs.patient_id = dp.patient_id
INNER JOIN dbo.dim_facility df
    ON fs.facility_id = df.facility_id
INNER JOIN dbo.dim_department dd
    ON fs.department_id = dd.department_id
LEFT JOIN dbo.dim_diagnosis dx
    ON fs.icd10_code = dx.icd10_code;

GO

-- Validation Queries
-- Row-count checks
SELECT 'patients_to_dim_patient' AS check_name, COUNT(*) AS row_count FROM dbo.dim_patient
UNION ALL
SELECT 'facilities_to_dim_facility', COUNT(*) FROM dbo.dim_facility
UNION ALL
SELECT 'departments_to_dim_department', COUNT(*) FROM dbo.dim_department
UNION ALL
SELECT 'fact_encounter_outcomes', COUNT(*) FROM dbo.fact_encounter_outcomes;

-- Validate one row per encounter in fact
SELECT
    encounter_id,
    COUNT(*) AS row_count
FROM dbo.fact_encounter_outcomes
GROUP BY encounter_id
HAVING COUNT(*) > 1;

-- Validate readmission flag counts
SELECT
    SUM(index_discharge_flag) AS index_discharges,
    SUM(readmission_30d_flag) AS readmission_30d_cases,
    SUM(readmission_count_30d) AS readmission_count_30d
FROM dbo.fact_encounter_outcomes;

-- Validate average LOS by facility and department
SELECT
    f.facility_name,
    d.department_name,
    AVG(CAST(feo.length_of_stay_days AS DECIMAL(10,2))) AS avg_length_of_stay
FROM dbo.fact_encounter_outcomes feo
INNER JOIN dbo.dim_facility f
    ON feo.facility_key = f.facility_key
INNER JOIN dbo.dim_department d
    ON feo.department_key = d.department_key
WHERE feo.length_of_stay_days IS NOT NULL
GROUP BY
    f.facility_name,
    d.department_name;

-- Validate known demo readmission scenario presence
SELECT
    dp.patient_id,
    feo.encounter_id,
    feo.discharge_date,
    feo.readmission_30d_flag
FROM dbo.fact_encounter_outcomes feo
INNER JOIN dbo.dim_patient dp
    ON feo.patient_key = dp.patient_key
WHERE dp.patient_id = 'P001';
